Linear design system updates
ably/ably-ui pull request #186
Opened 2022-05-19 14:50 UTC by dpiatek

Jira Ticket Link / Motivation
----

Implement:
https://app.asana.com/0/1202054865216493/1202146409149931/f
https://app.asana.com/0/1202054865216493/1202146409149933/f

Additionally:
- update paragraph text styles to correct color
- move Source Code Pro import to a separate file

Summary of changes
----

See commits for details.

How do you manually test this?
----

All changes can be review in the preview app (remotely or locally)

Reviewer Tasks (optional)
----

Merge/Deploy Checklist
----

- [ ] Written automated tests for implemented features/fixed bugs
- [ ] Rebased and squashed commits
- [ ] Commits have clear descriptions of their changes
- [ ] Checked for any performance regressions

Frontend Checklist
----

- [ ] No frontend changes in this PR
- [ ] Added before/after screenshots for changes
- [ ] Tested on different platforms/browsers with [Browserstack](https://www.browserstack.com)
- [ ] Compared with the initial design / our [brand guidelines](https://www.figma.com/file/jTQgyIovrhGBOf4Zrvjvbk/Ably-Linear-Design?node-id=118%3A0)
- [ ] Checked the code for accessibility issues ([VoiceOver User Guide](https://support.apple.com/en-gb/guide/voiceover/welcome/mac))?

2022-05-24 09:00 UTC, artismarti requested changes
as discussed on Tuple! :)

2022-05-24 09:00 UTC, artismarti commented on src/core/styles/properties.css
> +    --color-gui-visited: #4887c2;
This needs to be applied.

2022-05-24 09:00 UTC, artismarti commented on src/core/styles/text.css
> +    @apply visited:text-gui-viewed;
this needs to be `visited` :)

2022-05-24 09:24 UTC, artismarti approved these changes
🚀 
LGTM

2022-05-27 10:19 UTC, aralovelace approved these changes

2022-08-04 10:38 UTC, merged