Add storybook
ably/ably-ui pull request #302
Opened 2023-12-13 15:51 UTC by dpiatek

Jira Ticket Link / Motivation
----

Summary of changes
----

How do you manually test this?
----

Reviewer Tasks (optional)
----

Merge/Deploy Checklist
----

- [ ] Written automated tests for implemented features/fixed bugs
- [ ] Rebased and squashed commits
- [ ] Commits have clear descriptions of their changes
- [ ] Checked for any performance regressions

Frontend Checklist
----

- [ ] No frontend changes in this PR
- [ ] Added before/after screenshots for changes
- [ ] Tested on different platforms/browsers with [Browserstack](https://www.browserstack.com)
- [ ] Compared with the initial design / our [brand guidelines](https://www.figma.com/file/jTQgyIovrhGBOf4Zrvjvbk/Ably-Linear-Design?node-id=118%3A0)
- [ ] Checked the code for accessibility issues ([VoiceOver User Guide](https://support.apple.com/en-gb/guide/voiceover/welcome/mac))?

2024-03-18 21:19 UTC, kennethkalmer requested changes
This looks great @jamiehenson (and @dpiatek), thanks so much!

A few small comments to give it some shine :)

* Squash the existing featured link fixup commit down
* Squash `chore: don't allow SB version ads or telemetry` into `Add storybook scaffold`
* Drop the first commit, then `chore: resolve preview merge commit and remove TW base layer usage` will be reduced to only the meganav test data comment, and can be squashed into `feat: port existing ably-ui content to SB stories, strip out TW layer…`

(Be careful with the squashes, I can help if that would make it more comfortable)

2024-03-18 21:19 UTC, kennethkalmer commented on tailwind.config.js
> -    { pattern: /^hljs.*/ },
These are the syntax highlighter classes, is this okay to remove?

2024-03-19 11:42 UTC, jamiehenson commented
@kennethkalmer done the squashing, thanks for the suggestions.

2024-03-19 12:13 UTC, kennethkalmer approved these changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaXdianlkb2ZzbG1iNHh3Mmdwbm82NTFpajFnZTk3bmlkZ2JhYjIzdiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NjPEDD7S9Jssw/giphy.gif)

2024-03-20 11:10 UTC, merged