Update navigation to change  /chat & /pubsub URLs
ably/ably-ui pull request #455
Opened 2024-08-21 12:10 UTC by aralovelace

## Jira Ticket Link / Motivation

WEB-3968

## Summary of changes

## How do you manually test this?

## Reviewer Tasks (optional)

## Merge/Deploy Checklist

- [ ] Written automated tests for implemented features/fixed bugs
- [ ] Rebased and squashed commits
- [ ] Commits have clear descriptions of their changes
- [ ] Checked for any performance regressions

## Frontend Checklist

- [ ] No frontend changes in this PR
- [ ] Added before/after screenshots for changes
- [ ] Tested on different platforms/browsers with [Browserstack](https://www.browserstack.com)
- [ ] Compared with the initial design / our [brand guidelines](https://www.figma.com/file/jTQgyIovrhGBOf4Zrvjvbk/Ably-Linear-Design?node-id=118%3A0)
- [ ] Checked the code for accessibility issues ([VoiceOver User Guide](https://support.apple.com/en-gb/guide/voiceover/welcome/mac))?

2024-08-21 13:38 UTC, jamiehenson requested changes
There's a chat link in `MeganavContentProducts` that also needs to be updated

2024-08-21 14:08 UTC, aralovelace commented
> There's a chat link in `MeganavContentProducts` that also needs to be updated

Thanks for spotting it. Its now updated

2024-08-21 14:42 UTC, kennethkalmer approved these changes
Thanks @aralovelace 👏

2024-08-22 09:01 UTC, jamiehenson approved these changes

2024-08-22 09:13 UTC, merged