14.6.7 - Bordered pricing cards, static accordion themes, SB 8.3.5
ably/ably-ui pull request #505
Opened 2024-10-08 15:14 UTC by jamiehenson

## Jira Ticket Link / Motivation

The motivation lies within

## Summary of changes

A mixture of changes that benefit design requests for the pricing page and the pricing dashboards.

- for the pricing page, `static` and `darkStatic` themes for the `Accordion`. This is basically a hack to make it more like a table instead of retooling the table-ish bit of the pricing page to use a different component (`Accordion` was chosen for its expandable sections)
- for the dash, a `border` prop can be supplied to the data objects that go into the pricing card to give it a stylised border with some custom text. More on that here
- for both, the description section of the pricing/consumption cards adjusts to the height of the largest one in the set so that the CTAs stay in line

## How do you manually test this?

## Reviewer Tasks (optional)

## Merge/Deploy Checklist

- [ ] Written automated tests for implemented features/fixed bugs
- [ ] Rebased and squashed commits
- [ ] Commits have clear descriptions of their changes
- [ ] Checked for any performance regressions

## Frontend Checklist

- [ ] No frontend changes in this PR
- [ ] Added before/after screenshots for changes
- [ ] Tested on different platforms/browsers with [Browserstack](https://www.browserstack.com)
- [ ] Compared with the initial design / our [brand guidelines](https://www.figma.com/file/jTQgyIovrhGBOf4Zrvjvbk/Ably-Linear-Design?node-id=118%3A0)
- [ ] Checked the code for accessibility issues ([VoiceOver User Guide](https://support.apple.com/en-gb/guide/voiceover/welcome/mac))?

2024-10-08 15:25 UTC, jamiehenson commented on src/core/Accordion.tsx
> +  },
Good catch, but this is the intention in these scenarios.

2024-10-08 15:28 UTC, jamiehenson commented on src/core/Pricing/PricingCards.tsx
> +          ),
There is no `id` property, the titles will be distinct here.

2024-10-08 19:49 UTC, kennethkalmer reviewed
This looks so nice in Chrome, and then enter Safari 😭 

![ Pricing Cards - Docs ⋅ Storybook 2024-10-08 20-48-23](https://github.com/user-attachments/assets/3d1e186d-53b6-4ef9-be26-a96c2476fe72)

2024-10-09 12:27 UTC, aralovelace requested changes
blue border is not set yet for light theme

![image](https://github.com/user-attachments/assets/7a9354c9-e81a-4db1-9875-a10207188675)

2024-10-10 11:11 UTC, jamiehenson commented on src/core/Pricing/PricingCards.tsx
> +  }, [descriptionsRef.current]);
Good bunny

2024-10-10 11:22 UTC, jamiehenson commented on src/core/Pricing/PricingCards.tsx
> +  }, []);
Decent suggestions, but this is a static component with very few re-render cycles so the memoisation would appear to me to be an overoptimisation here

2024-10-10 11:42 UTC, kennethkalmer approved these changes
I'm happy with the Safari compatibility now! Maybe hold for an additional ✅ from @aralovelace to make sure she's happy as well?

2024-10-10 12:52 UTC, aralovelace approved these changes
⭐⭐⭐⭐⭐

2024-10-10 13:25 UTC, merged