[WEB-4082] General styling updates, add Radio buttons
ably/ably-ui pull request #561
Opened 2024-11-27 17:50 UTC by jamiehenson

## Jira Ticket Link / Motivation

## Summary of changes

## How do you manually test this?

## Reviewer Tasks (optional)

## Merge/Deploy Checklist

- [ ] Written automated tests for implemented features/fixed bugs
- [ ] Rebased and squashed commits
- [ ] Commits have clear descriptions of their changes
- [ ] Checked for any performance regressions

## Frontend Checklist

- [ ] No frontend changes in this PR
- [ ] Added before/after screenshots for changes
- [ ] Tested on different platforms/browsers with [Browserstack](https://www.browserstack.com)
- [ ] Compared with the initial design / our [brand guidelines](https://www.figma.com/file/jTQgyIovrhGBOf4Zrvjvbk/Ably-Linear-Design?node-id=118%3A0)
- [ ] Checked the code for accessibility issues ([VoiceOver User Guide](https://support.apple.com/en-gb/guide/voiceover/welcome/mac))?

2024-11-28 16:56 UTC, jamiehenson commented on tailwind.config.js
> +      menu4: ["var(--fs-menu4)"],
Don't worry mate it's used elsewhere

2024-11-29 11:18 UTC, jamiehenson commented on src/core/styles/Forms.stories.tsx
> +};
Done that

2024-11-29 15:59 UTC, kennethkalmer requested changes
Something is amiss with the checkboxes in dark mode ;)

![ Forms - Docs ⋅ Storybook 2024-11-29 15-59-12](https://github.com/user-attachments/assets/ec9a2896-b76f-455e-885f-77b57646a327)

2024-11-29 16:00 UTC, kennethkalmer commented on src/core/styles/legacy-buttons.css
> +    @apply hover:text-white hover:bg-neutral-1100;
![ Button (legacy) - Docs ⋅ Storybook 2024-11-29 16-00-23](https://github.com/user-attachments/assets/d8d0fae1-5067-42ab-b273-7a1e02478948)

2024-11-29 16:02 UTC, jamiehenson commented on src/core/styles/legacy-buttons.css
> +    @apply hover:text-white hover:bg-neutral-1100;
Chef Watson's request

2024-11-29 16:03 UTC, jamiehenson commented on src/core/styles/legacy-buttons.css
> +    @apply hover:text-white hover:bg-neutral-1100;
Worth bearing in mind that the legacy buttons aren't expected to have any dynamic dark mode support

2024-11-29 16:22 UTC, jamiehenson commented
@kennethkalmer updated the forms Storybook page, good to be consistent with new additions. Alas not on the Github pages instance as I have the Toggle/TabMenu components on there and those are a greater review priority for now

2024-12-02 13:41 UTC, kennethkalmer approved these changes
Nice one @jamiehenson 👏

2024-12-02 13:46 UTC, merged